language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
before_script: chmod +x gradlew
script:
  - jdk_switcher use oraclejdk8
  - ./gradlew build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master