language: java
sudo: false
install: true
addons:
  apt:
    packages:
      - oracle-java8-installer
before_script: chmod +x gradlew
script:
  - jdk_switcher use oraclejdk8
  - ./gradlew build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
    repo: git@github.com:FalseHonesty/FalseHonesty.github.io.git
    local_dir: /build/libs
    target_branch: master